In [1]:
from pandas import ExcelFile
from pandas import ExcelWriter


import flattentool
import pandas as pd

import numpy as np
import json


from redflags_20 import *
from appaltipop_20 import *
from shutil import copyfile

In [2]:

data_dir ='./dati/'
tmp_dir = './tmp/'
file_dir = './output/'

work_dir = data_dir 


ocds_file = "202006.json"
xlsx_file = "202006.xlsx"

In [3]:
es_out_ocds = os.path.join(work_dir, ocds_file)
es_out_xlsx = os.path.join(work_dir, xlsx_file)

In [4]:
excel_path = flattenocds (es_out_ocds, tmp_dir)
xls = pd.ExcelFile(excel_path)


#scrittura file xlsx nella directory x il download
copyfile(excel_path, es_out_xlsx)

'./dati/202006.xlsx'

In [5]:

df_releases = pd.read_excel(xls, 'releases')

df_awards = pd.read_excel(xls, 'rel_awards')

df_parties = pd.read_excel(xls, 'rel_parties')

df_trans = pd.read_excel(xls, 'rel_ten_items')

In [6]:
df_releases['releases/0/buyer/name'] = df_releases['releases/0/buyer/name'].str.upper()

df_releases['releases/0/tender/tenderPeriod/startDate'] = pd.to_datetime(df_releases['releases/0/tender/tenderPeriod/startDate'], errors = 'coerce')

df_releases['releases/0/tender/tenderPeriod/endDate'] = pd.to_datetime(df_releases['releases/0/tender/tenderPeriod/endDate'], errors = 'coerce')

df_releases.head()

,ocid,releases/0/id,releases/0/tender/id,releases/0/tender/description,releases/0/tender/value/amount,releases/0/tender/value/currency,releases/0/tender/mainProcurementCategory,releases/0/tender/procurementMethodDetails,releases/0/tender/tenderPeriod/startDate,releases/0/tender/tenderPeriod/endDate,releases/0/ocid,releases/0/date,releases/0/language,releases/0/tag,releases/0/initiationType,releases/0/buyer/id,releases/0/buyer/name
0,NaN,ocds-hu01ve-7784116-01,7784116,PROROGA POLIZZA KASKO DI N.12 MESI DAL 01/07/2...,145000.0,EUR,services,COD:4 ; TITLE:PROCEDURA NEGOZIATA SENZA PREVIA...,2020-06-03 12:00:00+00:00,2020-07-31 12:00:00+00:00,ocds-hu01ve-7784116,2021-07-24T12:00:00Z,ita,tender;award;contract,tender,02483810392,AZIENDA USL DELLA ROMAGNA
1,NaN,ocds-hu01ve-7787339-01,7787339,ID 2865 - FORNITURA DI PC PORTATILI PER GLI EN...,388306.2,EUR,goods,COD:27 ; TITLE:AFFIDAMENTO DIRETTO IN ADESIONE...,2020-06-08 12:00:00+00:00,2020-06-08 12:00:00+00:00,ocds-hu01ve-7787339,2021-07-24T12:00:00Z,ita,tender;award;contract,tender,00118410323,INSIEL SPA
2,NaN,ocds-hu01ve-7948849-01,7948849,CA 19 - AQ 397 - COMPLETAMENTO DEI LAVORI DI M...,998000.0,EUR,works,COD:27 ; TITLE:AFFIDAMENTO DIRETTO IN ADESIONE...,2020-06-22 12:00:00+00:00,2020-06-22 12:00:00+00:00,ocds-hu01ve-7948849,2021-11-30T12:00:00Z,ita,tender;award;contract,tender,01585570581,RETE FERROVIARIA ITALIANA - SOCIETA PER AZIONI
3,NaN,ocds-hu01ve-7790647-01,7790647,SERVIZIO DI RACCOLTA E TRASPORTO RSU ED ASSIMI...,732280.5,EUR,services,COD:1 ; TITLE:PROCEDURA APERTA,2020-06-16 12:00:00+00:00,2020-07-21 12:00:00+00:00,ocds-hu01ve-7790647,2021-10-28T12:00:00Z,ita,tender;award,tender,83001050752,COMUNE DI CARPIGNANO SALENTINO
4,NaN,ocds-hu01ve-7802578-01,7802578,APPALTO SPECIFICO PER L,233105687.2,EUR,goods,COD:7 ; TITLE:SISTEMA DINAMICO DI ACQUISIZIONE,2020-06-26 12:00:00+00:00,2020-07-23 12:00:00+00:00,ocds-hu01ve-7802578,2022-01-27T12:00:00Z,ita,tender;award,tender,80143490581,REGIONE LAZIO

In [7]:
df_releases_buyer = df_releases[['releases/0/id', 'releases/0/buyer/id', 'releases/0/buyer/name']]

df_releases_buyer.columns = ['ocds:releases/0/id', 'ocds:releases/0/buyer/id', 'ocds:releases/0/buyer/name']

df_releases_buyer.head()

,ocds:releases/0/id,ocds:releases/0/buyer/id,ocds:releases/0/buyer/name
0,ocds-hu01ve-7784116-01,02483810392,AZIENDA USL DELLA ROMAGNA
1,ocds-hu01ve-7787339-01,00118410323,INSIEL SPA
2,ocds-hu01ve-7948849-01,01585570581,RETE FERROVIARIA ITALIANA - SOCIETA PER AZIONI
3,ocds-hu01ve-7790647-01,83001050752,COMUNE DI CARPIGNANO SALENTINO
4,ocds-hu01ve-7802578-01,80143490581,REGIONE LAZIO

In [8]:
#df_parties

In [9]:
df_tenderers = df_parties[df_parties['releases/0/parties/0/roles'].str.contains('supplier')]

df_tenderers.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 12724 entries, 1 to 32546
Data columns (total 12 columns):
 #   Column                                      Non-Null Count  Dtype
---  ------                                      --------------  -----
 0   ocid                                        12724 non-null  object
 1   releases/0/id                               12724 non-null  object
 2   releases/0/parties/0/id                     12724 non-null  object
 3   releases/0/parties/0/name                   12724 non-null  object
 4   releases/0/parties/0/identifier/id          12724 non-null  object
 5   releases/0/parties/0/identifier/scheme      12724 non-null  object
 6   releases/0/parties/0/identifier/legalName   12724 non-null  object
 7   releases/0/parties/0/address/streetAddress  0 non-null      object
 8   releases/0/parties/0/address/locality       0 non-null      object
 9   releases/0/parties/0/address/postalCode     0 non-null      object
 10  releases/0/parties/0/address/countryName    0 non-null      object
 11  releases/0/parties/0/roles                  12724 non-null  object
dtypes: object(12)
memory usage: 1.3+ MB

In [10]:
df_participants =  create_participants(df_tenderers)

df_participants.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9902 entries, 0 to 9901
Data columns (total 4 columns):
 #   Column                                           Non-Null Count  Dtype
---  ------                                           --------------  -----
 0   ocds:releases/0/id                               9902 non-null   object
 1   appaltipop:releases/0/tender/participants/total  9902 non-null   int64
 2   appaltipop:releases/0/participants/total         9902 non-null   int64
 3   appaltipop:releases/0/participants/mean          9902 non-null   float64
dtypes: float64(1), int64(2), object(1)
memory usage: 309.6+ KB

In [11]:
df_suppliers_all = df_parties[df_parties['releases/0/parties/0/roles'].str.contains('supplier')]

df_suppliers = df_suppliers_all[['releases/0/id', 'releases/0/parties/0/id',
             'releases/0/parties/0/name'
    ]]

#df_suppliers = df_suppliers.drop_duplicates()

df_suppliers.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 12724 entries, 1 to 32546
Data columns (total 3 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   releases/0/id              12724 non-null  object
 1   releases/0/parties/0/id    12724 non-null  object
 2   releases/0/parties/0/name  12724 non-null  object
dtypes: object(3)
memory usage: 397.6+ KB

In [12]:

df_nContracts = create_nContracts(df_suppliers)

df_nContracts

,ocds:releases/0/parties/0/id,appaltipop:releases/0/supplier/tendersByBuyers/total
6187,09238800156,95
5979,08082461008,72
6477,11264670156,61
3686,02774840595,57
501,00488410010,52
...,...,...
2917,02198590248,1
2916,02198320232,1
2913,02197520592,1
2912,02196840645,1
7485,ZZRRSR68T10L740S,1

In [14]:

df_amountByBuyer = create_rel(df_releases, df_suppliers)
df_amountByBuyer.to_csv('amountByBuyer.csv', index = False, encoding='utf-8')

df_amountByBuyer

,ocds:releases/0/id,ocds:releases/0/buyer/id,ocds:releases/0/parties/0/id,appaltipop:releases/0/supplier/amountByBuyers/total
0,ocds-hu01ve-7369102-01,00484960588,01203960396,4000000.00
1,ocds-hu01ve-7369102-01,00484960588,01224630796,4000000.00
2,ocds-hu01ve-7369280-01,97220210583,00864500467,2200000.00
3,ocds-hu01ve-7369280-01,97220210583,04159770272,2200000.00
4,ocds-hu01ve-7466977-01,02438750586,08623131003,980000.00
...,...,...,...,...
12719,ocds-hu01ve-8477267-01,01742310152,03764000968,434639.99
12720,ocds-hu01ve-8477267-01,01742310152,80005530631,434639.99
12721,ocds-hu01ve-8499167-01,02438750586,01749530596,773362.30
12722,ocds-hu01ve-8501464-01,01263370635,02505861217,997996.67
12723,ocds-hu01ve-8522028-01,02438750586,11210601008,792997.85

In [15]:

df_final = pd.merge(df_releases, df_participants, how='outer', 
                    left_on='releases/0/id', 
                        right_on='ocds:releases/0/id')

df_final_flat = df_final[['releases/0/id', 'releases/0/tender/description', 'releases/0/tender/procurementMethodDetails',
             'releases/0/tender/tenderPeriod/startDate', 'releases/0/tender/tenderPeriod/endDate', 
             'releases/0/tender/value/amount', 'appaltipop:releases/0/tender/participants/total',
             'appaltipop:releases/0/participants/total', 'appaltipop:releases/0/participants/mean'
    ]]


df_final_flat.columns = ['ocds:releases/0/id', 'ocds:releases/0/tender/title', 'ocds:releases/0/tender/procurementMethodDetails',
                'ocds:releases/0/tender/contractPeriod/startDate', 'ocds:releases/0/tender/contractPeriod/endDate', 
                'ocds:releases/0/awards/0/value/amount', 'appaltipop:releases/0/tender/participants/total',
                'appaltipop:releases/0/participants/total', 'appaltipop:releases/0/participants/mean']
df_final_flat

,ocds:releases/0/id,ocds:releases/0/tender/title,ocds:releases/0/tender/procurementMethodDetails,ocds:releases/0/tender/contractPeriod/startDate,ocds:releases/0/tender/contractPeriod/endDate,ocds:releases/0/awards/0/value/amount,appaltipop:releases/0/tender/participants/total,appaltipop:releases/0/participants/total,appaltipop:releases/0/participants/mean
0,ocds-hu01ve-7784116-01,PROROGA POLIZZA KASKO DI N.12 MESI DAL 01/07/2...,COD:4 ; TITLE:PROCEDURA NEGOZIATA SENZA PREVIA...,2020-06-03 12:00:00+00:00,2020-07-31 12:00:00+00:00,1.450000e+05,1.0,12725.0,1.29
1,ocds-hu01ve-7787339-01,ID 2865 - FORNITURA DI PC PORTATILI PER GLI EN...,COD:27 ; TITLE:AFFIDAMENTO DIRETTO IN ADESIONE...,2020-06-08 12:00:00+00:00,2020-06-08 12:00:00+00:00,3.883062e+05,1.0,12725.0,1.29
2,ocds-hu01ve-7948849-01,CA 19 - AQ 397 - COMPLETAMENTO DEI LAVORI DI M...,COD:27 ; TITLE:AFFIDAMENTO DIRETTO IN ADESIONE...,2020-06-22 12:00:00+00:00,2020-06-22 12:00:00+00:00,9.980000e+05,2.0,12725.0,1.29
3,ocds-hu01ve-7790647-01,SERVIZIO DI RACCOLTA E TRASPORTO RSU ED ASSIMI...,COD:1 ; TITLE:PROCEDURA APERTA,2020-06-16 12:00:00+00:00,2020-07-21 12:00:00+00:00,7.322805e+05,1.0,12725.0,1.29
4,ocds-hu01ve-7802578-01,APPALTO SPECIFICO PER L,COD:7 ; TITLE:SISTEMA DINAMICO DI ACQUISIZIONE,2020-06-26 12:00:00+00:00,2020-07-23 12:00:00+00:00,2.331057e+08,7.0,12725.0,1.29
...,...,...,...,...,...,...,...,...,...
24698,ocds-hu01ve-7788105-01,MOBILETTO ODA N. 6700020100,COD:24 ; TITLE:AFFIDAMENTO DIRETTO,2020-06-04 12:00:00+00:00,2020-06-05 12:00:00+00:00,2.223000e+02,NaN,NaN,NaN
24699,ocds-hu01ve-7812002-01,PRESTAZIONE SERVIZIO 118 PRESSO IL TERRITORIO ...,COD:24 ; TITLE:AFFIDAMENTO DIRETTO,2020-06-01 12:00:00+00:00,2020-06-30 12:00:00+00:00,4.184078e+04,NaN,NaN,NaN
24700,ocds-hu01ve-7784054-01,MANUTENZIONE STRAORDINARIA DELLE STRADE PROVIN...,COD:34 ; TITLE:PROCEDURA NEGOZIATA PER AFFIDAM...,2020-06-09 12:00:00+00:00,2020-06-16 12:00:00+00:00,9.200000e+04,NaN,NaN,NaN
24701,ocds-hu01ve-7786740-01,SERVIZIO DI OFFICINA MECCANICA E REVISIONI MEZ...,COD:24 ; TITLE:AFFIDAMENTO DIRETTO,2020-06-05 12:00:00+00:00,2020-06-12 12:00:00+00:00,3.900000e+04,NaN,NaN,NaN
24702,ocds-hu01ve-7768868-01,LOTTO 1470 - ORFADIN - CIG DERIVATO,COD:27 ; TITLE:AFFIDAMENTO DIRETTO IN ADESIONE...,2020-06-10 12:00:00+00:00,2020-06-10 12:00:00+00:00,6.855504e+04,NaN,NaN,NaN

In [16]:


df_final_flat = create_final(df_releases, df_awards,  df_trans, df_participants)

df_final_flat

,ocds:releases/0/id,ocds:releases/0/tender/title,ocds:releases/0/tender/procurementMethodDetails,ocds:releases/0/tender/contractPeriod/startDate,ocds:releases/0/tender/contractPeriod/endDate,ocds:releases/0/awards/0/value/amount,appaltipop:releases/0/tender/participants/total,appaltipop:releases/0/participants/total,appaltipop:releases/0/participants/mean
0,ocds-hu01ve-7784116-01,PROROGA POLIZZA KASKO DI N.12 MESI DAL 01/07/2...,COD:4 ; TITLE:PROCEDURA NEGOZIATA SENZA PREVIA...,2020-06-03 12:00:00+00:00,2020-07-31 12:00:00+00:00,1.450000e+05,1.0,12725.0,1.29
1,ocds-hu01ve-7787339-01,ID 2865 - FORNITURA DI PC PORTATILI PER GLI EN...,COD:27 ; TITLE:AFFIDAMENTO DIRETTO IN ADESIONE...,2020-06-08 12:00:00+00:00,2020-06-08 12:00:00+00:00,3.883062e+05,1.0,12725.0,1.29
2,ocds-hu01ve-7948849-01,CA 19 - AQ 397 - COMPLETAMENTO DEI LAVORI DI M...,COD:27 ; TITLE:AFFIDAMENTO DIRETTO IN ADESIONE...,2020-06-22 12:00:00+00:00,2020-06-22 12:00:00+00:00,9.980000e+05,2.0,12725.0,1.29
3,ocds-hu01ve-7790647-01,SERVIZIO DI RACCOLTA E TRASPORTO RSU ED ASSIMI...,COD:1 ; TITLE:PROCEDURA APERTA,2020-06-16 12:00:00+00:00,2020-07-21 12:00:00+00:00,7.322805e+05,1.0,12725.0,1.29
4,ocds-hu01ve-7802578-01,APPALTO SPECIFICO PER L,COD:7 ; TITLE:SISTEMA DINAMICO DI ACQUISIZIONE,2020-06-26 12:00:00+00:00,2020-07-23 12:00:00+00:00,2.331057e+08,7.0,12725.0,1.29
...,...,...,...,...,...,...,...,...,...
24698,ocds-hu01ve-7788105-01,MOBILETTO ODA N. 6700020100,COD:24 ; TITLE:AFFIDAMENTO DIRETTO,2020-06-04 12:00:00+00:00,2020-06-05 12:00:00+00:00,2.223000e+02,NaN,NaN,NaN
24699,ocds-hu01ve-7812002-01,PRESTAZIONE SERVIZIO 118 PRESSO IL TERRITORIO ...,COD:24 ; TITLE:AFFIDAMENTO DIRETTO,2020-06-01 12:00:00+00:00,2020-06-30 12:00:00+00:00,4.184078e+04,NaN,NaN,NaN
24700,ocds-hu01ve-7784054-01,MANUTENZIONE STRAORDINARIA DELLE STRADE PROVIN...,COD:34 ; TITLE:PROCEDURA NEGOZIATA PER AFFIDAM...,2020-06-09 12:00:00+00:00,2020-06-16 12:00:00+00:00,9.200000e+04,NaN,NaN,NaN
24701,ocds-hu01ve-7786740-01,SERVIZIO DI OFFICINA MECCANICA E REVISIONI MEZ...,COD:24 ; TITLE:AFFIDAMENTO DIRETTO,2020-06-05 12:00:00+00:00,2020-06-12 12:00:00+00:00,3.900000e+04,NaN,NaN,NaN
24702,ocds-hu01ve-7768868-01,LOTTO 1470 - ORFADIN - CIG DERIVATO,COD:27 ; TITLE:AFFIDAMENTO DIRETTO IN ADESIONE...,2020-06-10 12:00:00+00:00,2020-06-10 12:00:00+00:00,6.855504e+04,NaN,NaN,NaN

### Calcolo dei Redflag

In [17]:
df_merge =  pd.merge(df_releases, df_tenderers, how='left', 
                   left_on='releases/0/id', 
                   right_on='releases/0/id')

df_merge.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 27525 entries, 0 to 27524
Data columns (total 28 columns):
 #   Column                                      Non-Null Count  Dtype
---  ------                                      --------------  -----
 0   ocid_x                                      0 non-null      float64
 1   releases/0/id                               27525 non-null  object
 2   releases/0/tender/id                        27525 non-null  int64
 3   releases/0/tender/description               27525 non-null  object
 4   releases/0/tender/value/amount              27525 non-null  float64
 5   releases/0/tender/value/currency            27525 non-null  object
 6   releases/0/tender/mainProcurementCategory   27525 non-null  object
 7   releases/0/tender/procurementMethodDetails  27525 non-null  object
 8   releases/0/tender/tenderPeriod/startDate    27525 non-null  datetime64[ns, UTC]
 9   releases/0/tender/tenderPeriod/endDate      27476 non-null  datetime64[ns, UTC]
 10  releases/0/ocid                             27525 non-null  object
 11  releases/0/date                             27525 non-null  object
 12  releases/0/language                         27525 non-null  object
 13  releases/0/tag                              27525 non-null  object
 14  releases/0/initiationType                   27525 non-null  object
 15  releases/0/buyer/id                         27525 non-null  object
 16  releases/0/buyer/name                       27525 non-null  object
 17  ocid_y                                      12724 non-null  object
 18  releases/0/parties/0/id                     12724 non-null  object
 19  releases/0/parties/0/name                   12724 non-null  object
 20  releases/0/parties/0/identifier/id          12724 non-null  object
 21  releases/0/parties/0/identifier/scheme      12724 non-null  object
 22  releases/0/parties/0/identifier/legalName   12724 non-null  object
 23  releases/0/parties/0/address/streetAddress  0 non-null      object
 24  releases/0/parties/0/address/locality       0 non-null      object
 25  releases/0/parties/0/address/postalCode     0 non-null      object
 26  releases/0/parties/0/address/countryName    0 non-null      object
 27  releases/0/parties/0/roles                  12724 non-null  object
dtypes: datetime64[ns, UTC](2), float64(2), int64(1), object(23)
memory usage: 6.1+ MB

In [18]:
competitiveList= ["COD:1 ; TITLE:PROCEDURA APERTA", 
"COD:2 ; TITLE:PROCEDURA RISTRETTA", 
"COD:4 ; TITLE:PROCEDURA NEGOZIATA SENZA PREVIA PUBBLICAZIONE", 
"COD:5 ; TITLE:DIALOGO COMPETITIVO", 
"COD:6 ; TITLE:PROCEDURA NEGOZIATA SENZA PREVIA INDIZIONE DI GARA (SETTORI SPECIALI)", 
"COD:7 ; TITLE:SISTEMA DINAMICO DI ACQUISIZIONE", 
"COD:23 ; TITLE:PROCEDURA NEGOZIATA CON PREVIA INDIZIONE DI GARA (SETTORI SPECIALI)", 
"COD:28 ; TITLE:CONFRONTO COMPETITIVO IN ADESIONE AD ACCORDO QUADRO/CONVENZIONE",
"COD:29 ; TITLE:PROCEDURA AI SENSI DEI REGOLAMENTI DEGLI ORGANI COSTITUZIONALI",
"COD:33 ; TITLE:AFFIDAMENTO RISERVATO",
"COD:34 ; TITLE:PROCEDURA NEGOZIATA PER AFFIDAMENTI SOTTO SOGLIA",
"COD:35 ; TITLE:PROCEDURA ART.16 COMMA 2-BIS DPR 380/2001 PER OPERE URBANIZZAZIONE A SCOMPUTO PRIMARIE SOTTO SOGLIA COMUNITARIA",
"COD:36 ; TITLE:PARTERNARIATO PER L’INNOVAZIONE",
"COD:38 ; TITLE:PROCEDURA COMPETITIVA CON NEGOZIAZIONE",
]

df_r1 = redflag_01 (df_merge, 'releases/0/id', 'releases/0/tender/procurementMethodDetails', competitiveList)

df_r1.head()

,ocds:releases/0/id,appaltipop:releases/0/redflag/code,appaltipop:releases/0/redflag/description
0,ocds-hu01ve-6030690-01,01,Basso numero di offerenti medi di gara per pro...
1,ocds-hu01ve-7369280-01,01,Basso numero di offerenti medi di gara per pro...
2,ocds-hu01ve-7466977-01,01,Basso numero di offerenti medi di gara per pro...
3,ocds-hu01ve-7485593-01,01,Basso numero di offerenti medi di gara per pro...
4,ocds-hu01ve-7515616-01,01,Basso numero di offerenti medi di gara per pro...

In [19]:


df_r2 = redflag_02 (df_merge, 'releases/0/id', 'releases/0/tender/procurementMethodDetails', competitiveList)

df_r2.head()

,ocds:releases/0/id,appaltipop:releases/0/redflag/code,appaltipop:releases/0/redflag/description
0,ocds-hu01ve-6030690-01,02,Bassa percentuale di offerte aggiudicate media...
1,ocds-hu01ve-7369280-01,02,Bassa percentuale di offerte aggiudicate media...
2,ocds-hu01ve-7466977-01,02,Bassa percentuale di offerte aggiudicate media...
3,ocds-hu01ve-7485593-01,02,Bassa percentuale di offerte aggiudicate media...
4,ocds-hu01ve-7515616-01,02,Bassa percentuale di offerte aggiudicate media...

In [20]:
directList= [
"COD:24 ; TITLE:AFFIDAMENTO DIRETTO", 
"COD:25 ; TITLE:AFFIDAMENTO DIRETTO A SOCIETA' IN HOUSE", 
"COD:26 ; TITLE:AFFIDAMENTO DIRETTO A SOCIETA' RAGGRUPPATE/CONSORZIATE O CONTROLLATE NELLE CONCESSIONI E NEI PARTENARIATI", 
"COD:27 ; TITLE:AFFIDAMENTO DIRETTO IN ADESIONE AD ACCORDO QUADRO/CONVENZIONE",    
"COD:32 ; TITLE:AFFIDAMENTO DIRETTO PER VARIANTE SUPERIORE AL 20% DELL'IMPORTO CONTRATTUALE",
"COD:40 ; TITLE:AFFIDAMENTO DIRETTO PER MODIFICHE CONTRATTUALI O VARIANTI PER LE QUALI È NECESSARIA UNA NUOVA PROCEDURA DI AFFIDAMENTO"
               ]

df_r3 = redflag_03 (df_merge, 'releases/0/id', 'releases/0/tender/procurementMethodDetails', directList)

df_r3.head()

,ocds:releases/0/id,appaltipop:releases/0/redflag/code,appaltipop:releases/0/redflag/description
0,ocds-hu01ve-4949438-01,03,Questa gara presenta un solo offerente
1,ocds-hu01ve-6030690-01,03,Questa gara presenta un solo offerente
4,ocds-hu01ve-7466977-01,03,Questa gara presenta un solo offerente
5,ocds-hu01ve-7485593-01,03,Questa gara presenta un solo offerente
6,ocds-hu01ve-7515616-01,03,Questa gara presenta un solo offerente

In [21]:



df_r4 = redflag_04(df_tenderers, df_suppliers, 'releases/0/parties/0/id', 'releases/0/id')

df_r4

,ocds:releases/0/id,appaltipop:releases/0/redflag/code,appaltipop:releases/0/redflag/description
0,ocds-hu01ve-7784116-01,04,Il partecipante che non ha mai fatto un'offert...
1,ocds-hu01ve-7787339-01,04,Il partecipante che non ha mai fatto un'offert...
2,ocds-hu01ve-7948849-01,04,Il partecipante che non ha mai fatto un'offert...
3,ocds-hu01ve-7948849-01,04,Il partecipante che non ha mai fatto un'offert...
4,ocds-hu01ve-7790647-01,04,Il partecipante che non ha mai fatto un'offert...
...,...,...,...
7481,ocds-hu01ve-7789504-01,04,Il partecipante che non ha mai fatto un'offert...
7482,ocds-hu01ve-7795052-01,04,Il partecipante che non ha mai fatto un'offert...
7483,ocds-hu01ve-7802810-01,04,Il partecipante che non ha mai fatto un'offert...
7484,ocds-hu01ve-7781795-01,04,Il partecipante che non ha mai fatto un'offert...
7485,ocds-hu01ve-7765609-01,04,Il partecipante che non ha mai fatto un'offert...

In [22]:
df_suppliers_complete = pd.merge(df_suppliers, df_awards, how='outer', 
                   left_on='releases/0/id', 
                   right_on='releases/0/id')

df_suppliers_complete.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 181460 entries, 0 to 181459
Data columns (total 10 columns):
 #   Column                              Non-Null Count   Dtype
---  ------                              --------------   -----
 0   releases/0/id                       181460 non-null  object
 1   releases/0/parties/0/id             181426 non-null  object
 2   releases/0/parties/0/name           181426 non-null  object
 3   ocid                                181460 non-null  object
 4   releases/0/awards/0/id              181460 non-null  int64
 5   releases/0/awards/0/status          181460 non-null  object
 6   releases/0/awards/0/date            181452 non-null  object
 7   releases/0/awards/0/value/amount    181453 non-null  float64
 8   releases/0/awards/0/value/currency  181460 non-null  object
 9   releases/0/awards/0/relatedLots     181460 non-null  object
dtypes: float64(1), int64(1), object(8)
memory usage: 15.2+ MB

In [23]:

df_r5 = redflag_05 (df_suppliers_complete, 'releases/0/id', 'releases/0/awards/0/value/amount')


df_r5

Empty DataFrame
Columns: [releases/0/id, appaltipop:releases/0/redflag/code, appaltipop:releases/0/redflag/description]
Index: []

In [24]:
#df_rf = df_r1.append(df_r2, ignore_index=True) 
df_r2 = df_r2.reset_index(drop=True)
df_r3 = df_r3.reset_index(drop=True)
df_r4 = df_r4.reset_index(drop=True)
df_r5 = df_r5.reset_index(drop=True)

dfList = [df_r1, df_r2, df_r3, df_r4, df_r5]
df_rf= pd.concat(dfList, axis=0, sort=False)
df_rf.drop_duplicates(keep='first',inplace=True)

In [25]:
df_rf.head()

,ocds:releases/0/id,appaltipop:releases/0/redflag/code,appaltipop:releases/0/redflag/description,releases/0/id
0,ocds-hu01ve-6030690-01,01,Basso numero di offerenti medi di gara per pro...,NaN
1,ocds-hu01ve-7369280-01,01,Basso numero di offerenti medi di gara per pro...,NaN
2,ocds-hu01ve-7466977-01,01,Basso numero di offerenti medi di gara per pro...,NaN
3,ocds-hu01ve-7485593-01,01,Basso numero di offerenti medi di gara per pro...,NaN
4,ocds-hu01ve-7515616-01,01,Basso numero di offerenti medi di gara per pro...,NaN

In [26]:
k = (df_rf.groupby(['ocds:releases/0/id'])
            .apply(lambda x: x[['appaltipop:releases/0/redflag/code', 'appaltipop:releases/0/redflag/description']].to_dict('records'))
             .reset_index()
             .rename(columns={0:'appaltipop:releases/0/redflags'}))


k.head()

       ocds:releases/0/id                     appaltipop:releases/0/redflags
0  ocds-hu01ve-4949438-01  [{'appaltipop:releases/0/redflag/code': '03', ...
1  ocds-hu01ve-6030690-01  [{'appaltipop:releases/0/redflag/code': '01', ...
2  ocds-hu01ve-7369102-01  [{'appaltipop:releases/0/redflag/code': '04', ...
3  ocds-hu01ve-7369280-01  [{'appaltipop:releases/0/redflag/code': '01', ...
4  ocds-hu01ve-7466977-01  [{'appaltipop:releases/0/redflag/code': '01', ...

In [27]:
k1 = pd.merge(df_releases, k, how='left', 
                   left_on='releases/0/id', 
                   right_on='ocds:releases/0/id')

k2 = k1[['releases/0/id','appaltipop:releases/0/redflags']]

k2

,releases/0/id,appaltipop:releases/0/redflags
0,ocds-hu01ve-7784116-01,"[{'appaltipop:releases/0/redflag/code': '01', ..."
1,ocds-hu01ve-7787339-01,"[{'appaltipop:releases/0/redflag/code': '04', ..."
2,ocds-hu01ve-7948849-01,"[{'appaltipop:releases/0/redflag/code': '04', ..."
3,ocds-hu01ve-7790647-01,"[{'appaltipop:releases/0/redflag/code': '01', ..."
4,ocds-hu01ve-7802578-01,"[{'appaltipop:releases/0/redflag/code': '01', ..."
...,...,...
24698,ocds-hu01ve-7788105-01,NaN
24699,ocds-hu01ve-7812002-01,NaN
24700,ocds-hu01ve-7784054-01,"[{'appaltipop:releases/0/redflag/code': '01', ..."
24701,ocds-hu01ve-7786740-01,NaN
24702,ocds-hu01ve-7768868-01,NaN

In [28]:
red = df_releases['releases/0/id']
red1 = red.to_frame()
red1.reset_index(inplace=False)
red1['appaltipop:releases/0/redflags'] = [np.empty(0,dtype=float)]*len(red1)

red1

                releases/0/id appaltipop:releases/0/redflags
0      ocds-hu01ve-7784116-01                             []
1      ocds-hu01ve-7787339-01                             []
2      ocds-hu01ve-7948849-01                             []
3      ocds-hu01ve-7790647-01                             []
4      ocds-hu01ve-7802578-01                             []
...                       ...                            ...
24698  ocds-hu01ve-7788105-01                             []
24699  ocds-hu01ve-7812002-01                             []
24700  ocds-hu01ve-7784054-01                             []
24701  ocds-hu01ve-7786740-01                             []
24702  ocds-hu01ve-7768868-01                             []

[24703 rows x 2 columns]

In [29]:

k2['red'] = [np.empty(0,dtype=float)]*len(k2)

k2

/home/patruno/.local/share/virtualenvs/ocds-Sbk81Xh7/lib/python3.7/site-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.

,releases/0/id,appaltipop:releases/0/redflags,red
0,ocds-hu01ve-7784116-01,"[{'appaltipop:releases/0/redflag/code': '01', ...",[]
1,ocds-hu01ve-7787339-01,"[{'appaltipop:releases/0/redflag/code': '04', ...",[]
2,ocds-hu01ve-7948849-01,"[{'appaltipop:releases/0/redflag/code': '04', ...",[]
3,ocds-hu01ve-7790647-01,"[{'appaltipop:releases/0/redflag/code': '01', ...",[]
4,ocds-hu01ve-7802578-01,"[{'appaltipop:releases/0/redflag/code': '01', ...",[]
...,...,...,...
24698,ocds-hu01ve-7788105-01,NaN,[]
24699,ocds-hu01ve-7812002-01,NaN,[]
24700,ocds-hu01ve-7784054-01,"[{'appaltipop:releases/0/redflag/code': '01', ...",[]
24701,ocds-hu01ve-7786740-01,NaN,[]
24702,ocds-hu01ve-7768868-01,NaN,[]

In [30]:
k2['red']  = np.where(k2['appaltipop:releases/0/redflags'].notnull(), k2['appaltipop:releases/0/redflags'], k2['red'])
#k2['red'] = np.where(k2['appaltipop:releases/0/redflags'].notnull(), k2['appaltipop:releases/0/redflags'], k2['red'])

k2

/home/patruno/.local/share/virtualenvs/ocds-Sbk81Xh7/lib/python3.7/site-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.

,releases/0/id,appaltipop:releases/0/redflags,red
0,ocds-hu01ve-7784116-01,"[{'appaltipop:releases/0/redflag/code': '01', ...","[{'appaltipop:releases/0/redflag/code': '01', ..."
1,ocds-hu01ve-7787339-01,"[{'appaltipop:releases/0/redflag/code': '04', ...","[{'appaltipop:releases/0/redflag/code': '04', ..."
2,ocds-hu01ve-7948849-01,"[{'appaltipop:releases/0/redflag/code': '04', ...","[{'appaltipop:releases/0/redflag/code': '04', ..."
3,ocds-hu01ve-7790647-01,"[{'appaltipop:releases/0/redflag/code': '01', ...","[{'appaltipop:releases/0/redflag/code': '01', ..."
4,ocds-hu01ve-7802578-01,"[{'appaltipop:releases/0/redflag/code': '01', ...","[{'appaltipop:releases/0/redflag/code': '01', ..."
...,...,...,...
24698,ocds-hu01ve-7788105-01,NaN,[]
24699,ocds-hu01ve-7812002-01,NaN,[]
24700,ocds-hu01ve-7784054-01,"[{'appaltipop:releases/0/redflag/code': '01', ...","[{'appaltipop:releases/0/redflag/code': '01', ..."
24701,ocds-hu01ve-7786740-01,NaN,[]
24702,ocds-hu01ve-7768868-01,NaN,[]

In [31]:
df_final_redflags = k2[['releases/0/id', 'red']]

df_final_redflags.columns = ['ocds:releases/0/id', 'appaltipop:releases/0/redflags']

df_final_redflags

,ocds:releases/0/id,appaltipop:releases/0/redflags
0,ocds-hu01ve-7784116-01,"[{'appaltipop:releases/0/redflag/code': '01', ..."
1,ocds-hu01ve-7787339-01,"[{'appaltipop:releases/0/redflag/code': '04', ..."
2,ocds-hu01ve-7948849-01,"[{'appaltipop:releases/0/redflag/code': '04', ..."
3,ocds-hu01ve-7790647-01,"[{'appaltipop:releases/0/redflag/code': '01', ..."
4,ocds-hu01ve-7802578-01,"[{'appaltipop:releases/0/redflag/code': '01', ..."
...,...,...
24698,ocds-hu01ve-7788105-01,[]
24699,ocds-hu01ve-7812002-01,[]
24700,ocds-hu01ve-7784054-01,"[{'appaltipop:releases/0/redflag/code': '01', ..."
24701,ocds-hu01ve-7786740-01,[]
24702,ocds-hu01ve-7768868-01,[]

### Creazione dataframe finali e trasformazione in Json

## Creazione array dei suppliers

In [32]:

df_final_suppliers = create_final_suppliers(df_releases, df_suppliers, df_amountByBuyer, df_nContracts)

df_final_suppliers.to_csv('df_final_suppliers.csv', index = False, encoding='utf-8')

df_final_suppliers

,ocds:releases/0/id,appaltipop:releases/0/suppliers
0,ocds-hu01ve-7784116-01,[{'ocds:releases/0/parties/0/id': '01329510158...
1,ocds-hu01ve-7787339-01,[{'ocds:releases/0/parties/0/id': '04472901000...
2,ocds-hu01ve-7948849-01,[{'ocds:releases/0/parties/0/id': '06640370638...
3,ocds-hu01ve-7790647-01,[{'ocds:releases/0/parties/0/id': '02051620751...
4,ocds-hu01ve-7802578-01,[{'ocds:releases/0/parties/0/id': '00212840235...
...,...,...
24698,ocds-hu01ve-7788105-01,[]
24699,ocds-hu01ve-7812002-01,[]
24700,ocds-hu01ve-7784054-01,[]
24701,ocds-hu01ve-7786740-01,[]
24702,ocds-hu01ve-7768868-01,[]

In [33]:



df_final_buyers =  create_final_buyers(df_releases_buyer)

df_final_buyers

,ocds:releases/0/id,appaltipop:releases/0/buyers
0,ocds-hu01ve-4949438-01,"[{'ocds:releases/0/buyer/id': '82501750010', '..."
1,ocds-hu01ve-6030690-01,"[{'ocds:releases/0/buyer/id': '00088570569', '..."
2,ocds-hu01ve-7369102-01,"[{'ocds:releases/0/buyer/id': '00484960588', '..."
3,ocds-hu01ve-7369280-01,"[{'ocds:releases/0/buyer/id': '97220210583', '..."
4,ocds-hu01ve-7463633-01,"[{'ocds:releases/0/buyer/id': '94032920541', '..."
...,...,...
24698,ocds-hu01ve-8499167-01,"[{'ocds:releases/0/buyer/id': '02438750586', '..."
24699,ocds-hu01ve-8501464-01,"[{'ocds:releases/0/buyer/id': '01263370635', '..."
24700,ocds-hu01ve-8509057-01,"[{'ocds:releases/0/buyer/id': '01263370635', '..."
24701,ocds-hu01ve-8511583-01,"[{'ocds:releases/0/buyer/id': '97350070583', '..."
24702,ocds-hu01ve-8522028-01,"[{'ocds:releases/0/buyer/id': '02438750586', '..."

In [34]:
 df_final_a = pd.merge(df_final_suppliers, df_final_buyers, how='inner', 
                   left_on='ocds:releases/0/id', 
                    right_on='ocds:releases/0/id')

In [35]:
    df_final_array = pd.merge(df_final_a, df_final_redflags, how='inner', 
                    left_on='ocds:releases/0/id', 
                        right_on='ocds:releases/0/id')  

    df_final_array

,ocds:releases/0/id,appaltipop:releases/0/suppliers,appaltipop:releases/0/buyers,appaltipop:releases/0/redflags
0,ocds-hu01ve-7784116-01,[{'ocds:releases/0/parties/0/id': '01329510158...,"[{'ocds:releases/0/buyer/id': '02483810392', '...","[{'appaltipop:releases/0/redflag/code': '01', ..."
1,ocds-hu01ve-7787339-01,[{'ocds:releases/0/parties/0/id': '04472901000...,"[{'ocds:releases/0/buyer/id': '00118410323', '...","[{'appaltipop:releases/0/redflag/code': '04', ..."
2,ocds-hu01ve-7948849-01,[{'ocds:releases/0/parties/0/id': '06640370638...,"[{'ocds:releases/0/buyer/id': '01585570581', '...","[{'appaltipop:releases/0/redflag/code': '04', ..."
3,ocds-hu01ve-7790647-01,[{'ocds:releases/0/parties/0/id': '02051620751...,"[{'ocds:releases/0/buyer/id': '83001050752', '...","[{'appaltipop:releases/0/redflag/code': '01', ..."
4,ocds-hu01ve-7802578-01,[{'ocds:releases/0/parties/0/id': '00212840235...,"[{'ocds:releases/0/buyer/id': '80143490581', '...","[{'appaltipop:releases/0/redflag/code': '01', ..."
...,...,...,...,...
24698,ocds-hu01ve-7788105-01,[],"[{'ocds:releases/0/buyer/id': '05175700482', '...",[]
24699,ocds-hu01ve-7812002-01,[],"[{'ocds:releases/0/buyer/id': '03499370710', '...",[]
24700,ocds-hu01ve-7784054-01,[],"[{'ocds:releases/0/buyer/id': '00311260095', '...","[{'appaltipop:releases/0/redflag/code': '01', ..."
24701,ocds-hu01ve-7786740-01,[],"[{'ocds:releases/0/buyer/id': '07516911000', '...",[]
24702,ocds-hu01ve-7768868-01,[],"[{'ocds:releases/0/buyer/id': '11632570013', '...",[]

In [36]:
df_final_flat

,ocds:releases/0/id,ocds:releases/0/tender/title,ocds:releases/0/tender/procurementMethodDetails,ocds:releases/0/tender/contractPeriod/startDate,ocds:releases/0/tender/contractPeriod/endDate,ocds:releases/0/awards/0/value/amount,appaltipop:releases/0/tender/participants/total,appaltipop:releases/0/participants/total,appaltipop:releases/0/participants/mean
0,ocds-hu01ve-7784116-01,PROROGA POLIZZA KASKO DI N.12 MESI DAL 01/07/2...,COD:4 ; TITLE:PROCEDURA NEGOZIATA SENZA PREVIA...,2020-06-03 12:00:00+00:00,2020-07-31 12:00:00+00:00,1.450000e+05,1.0,12725.0,1.29
1,ocds-hu01ve-7787339-01,ID 2865 - FORNITURA DI PC PORTATILI PER GLI EN...,COD:27 ; TITLE:AFFIDAMENTO DIRETTO IN ADESIONE...,2020-06-08 12:00:00+00:00,2020-06-08 12:00:00+00:00,3.883062e+05,1.0,12725.0,1.29
2,ocds-hu01ve-7948849-01,CA 19 - AQ 397 - COMPLETAMENTO DEI LAVORI DI M...,COD:27 ; TITLE:AFFIDAMENTO DIRETTO IN ADESIONE...,2020-06-22 12:00:00+00:00,2020-06-22 12:00:00+00:00,9.980000e+05,2.0,12725.0,1.29
3,ocds-hu01ve-7790647-01,SERVIZIO DI RACCOLTA E TRASPORTO RSU ED ASSIMI...,COD:1 ; TITLE:PROCEDURA APERTA,2020-06-16 12:00:00+00:00,2020-07-21 12:00:00+00:00,7.322805e+05,1.0,12725.0,1.29
4,ocds-hu01ve-7802578-01,APPALTO SPECIFICO PER L,COD:7 ; TITLE:SISTEMA DINAMICO DI ACQUISIZIONE,2020-06-26 12:00:00+00:00,2020-07-23 12:00:00+00:00,2.331057e+08,7.0,12725.0,1.29
...,...,...,...,...,...,...,...,...,...
24698,ocds-hu01ve-7788105-01,MOBILETTO ODA N. 6700020100,COD:24 ; TITLE:AFFIDAMENTO DIRETTO,2020-06-04 12:00:00+00:00,2020-06-05 12:00:00+00:00,2.223000e+02,NaN,NaN,NaN
24699,ocds-hu01ve-7812002-01,PRESTAZIONE SERVIZIO 118 PRESSO IL TERRITORIO ...,COD:24 ; TITLE:AFFIDAMENTO DIRETTO,2020-06-01 12:00:00+00:00,2020-06-30 12:00:00+00:00,4.184078e+04,NaN,NaN,NaN
24700,ocds-hu01ve-7784054-01,MANUTENZIONE STRAORDINARIA DELLE STRADE PROVIN...,COD:34 ; TITLE:PROCEDURA NEGOZIATA PER AFFIDAM...,2020-06-09 12:00:00+00:00,2020-06-16 12:00:00+00:00,9.200000e+04,NaN,NaN,NaN
24701,ocds-hu01ve-7786740-01,SERVIZIO DI OFFICINA MECCANICA E REVISIONI MEZ...,COD:24 ; TITLE:AFFIDAMENTO DIRETTO,2020-06-05 12:00:00+00:00,2020-06-12 12:00:00+00:00,3.900000e+04,NaN,NaN,NaN
24702,ocds-hu01ve-7768868-01,LOTTO 1470 - ORFADIN - CIG DERIVATO,COD:27 ; TITLE:AFFIDAMENTO DIRETTO IN ADESIONE...,2020-06-10 12:00:00+00:00,2020-06-10 12:00:00+00:00,6.855504e+04,NaN,NaN,NaN

In [37]:
    df_final_all = pd.merge(df_final_array, df_final_flat, how='inner', 
                   left_on='ocds:releases/0/id', 
                    right_on='ocds:releases/0/id')

In [38]:
df_final_all = create_final_all(df_final_suppliers, df_final_buyers, df_final_redflags, df_final_flat)

#df_final_all

In [39]:
json_final_all = df_final_all.to_json(orient='records', date_format='iso')

In [40]:

filename = '202006_appaltipop' + '.json'

out_report = os.path.join(file_dir, filename)
out_report

# create and open file
f = open(out_report,"w")

# write data to file 
f.write(json_final_all)



# close file
f.close()